DROP TABLE IF EXISTS RECEITA;
CREATE TABLE RECEITA (
id int PRIMARY KEY,
data VARCHAR(50) NOT NULL,
descricao VARCHAR(50) NOT NULL,
valor int NOT NULL
);

DROP TABLE IF EXISTS DESPESA;
CREATE TABLE DESPESA (
id int PRIMARY KEY,
data VARCHAR(50) NOT NULL,
descricao VARCHAR(50) NOT NULL,
categoria VARCHAR(50),
valor int NOT NULL
);
