DROP TABLE IF EXISTS RECEITA;
CREATE TABLE RECEITA (
receita_id int PRIMARY KEY,
data_receita VARCHAR(50) NOT NULL,
descricao VARCHAR(50) NOT NULL,
valor int NOT NULL
);

DROP TABLE IF EXISTS DESPESA;
CREATE TABLE DESPESA (
despesa_id int PRIMARY KEY,
data_despesa VARCHAR(50) NOT NULL,
descricao VARCHAR(50) NOT NULL,
categoria VARCHAR(50) NOT NULL,
valor int NOT NULL
);
